### ISSUE TITLE
Recurring Profile 

### ISSUE THREAD

**Issue by kandhaguruv** [adam-paterson/magento-ce-1.9.0.1#1]
Hi Team,
In Recurring profile view page cancel button are not showing. Default package it is working fine. rwd package not showing cancel button.(sales/recurring_profile/view)
Thanks & Regards
Kandha guru. V

**Comment by adam-paterson** [comment]
Hi @kandhaguruv, I'm sorry I've only just seen this comment. Are you aware that this is only a mirror of Magento's official release to aid my development.

I'd recommend reporting any bugs to Magento directly. Their issue tracker can be found [here](http://www.magentocommerce.com/bug-tracking)
