### ISSUE TITLE
Unable to save the invoice Magento 1.9.1.1

### ISSUE THREAD

**Issue by neerajmagento** [adam-paterson/magento-ce-1.9.0.1#3]
I m using payment method sage pay. When i m submit my invoice with payment sagepay i m not able to save invoice. When other payment method use then save the invoice. Please help me for this issue.

**Comment by adam-paterson** [comment]
Hi @neerajmagento,

This is a mirror of Magento CE 1.9.1.1 and not the correct place to ask questions like this. I'd recommend posting your question to https://magento.stackexchange.com/
